services:
  charts-components_dev_web:
    image: charts-components_dev_web            # Docker image name
    container_name: charts-components_dev_web   # Docker container name
    build: ./web                                   # Build images with this ./Dockerfile
    volumes:
      - ../..:/home/node/app                   # Mount this code sources (../..) in container
    environment:
      - TZ=Europe/Paris
    env_file:
      - ./docker-compose.env
    ports:
      - "8080:3000"

networks:
    default:
        name: charts-components_network
